✨ Add logger pipe command
marcelropos/HM-DiscordBot pull request #196
Opened 2023-12-30 11:44 UTC by schitcrafter

2024-01-03 14:25 UTC, maxwai requested changes
A few small things.

Also after looking at the code it doesn't really make sense to allow the main log pipe to be changed, it should just always be the first channel. Not a lot needs to change, only the methods to change the log pipe and the not needed `sent_in_main_guild` calls. The `mysql_lib::get_guild` call doesn't need additional checks since the main guild is never in the database.

2024-01-03 14:25 UTC, maxwai commented on src/bot/checks.rs
> +pub async fn is_bot_admin(ctx: Context<'_>) -> Option<bool> {
I don't think None is very useful here as this should just be interpreted as false. The Methods calling this shouldn't actually care why a check returns false, only that the user doesn't have the permission to do so.

2024-01-03 14:25 UTC, maxwai commented on src/bot/commands.rs
> +        );
if not log pipe was setup, the user will not get any feedback from the command

2024-01-03 15:43 UTC, maxwai reviewed
looks good, will not merge yet since I want to test it first but can't right now

2024-02-11 11:59 UTC, maxwai commented
After trying the code, the log messages are not send in Discord. I found that it doesn't work when used inside `block_on` (don't know why), but wrapping it in a `spawn_blocking` makes it work.
@schitcrafter look at the changes and merge if the changes are fine for you

2024-02-11 11:59 UTC, maxwai approved these changes

2024-02-11 12:19 UTC, schitcrafter commented
Gonna take a guess that tracing didn't like blocking in it's layer (it's calling from an async context, so tokio, which also doesn't like blocking), that's probably why spawning is necessary. Probably should've been that from the beginning to be honest.

For the `LOG_LEVEL` thing, I was under the impression that fmt already comes with an EnvFilter (it only does when using its `init()` function) - but I still think that we should use [EnvFilter](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html). You can set the log level like you do manually here, but you also have much finer control about what to log (like switching to trace only for some module/crate/function/whatever). That's very nice for debugging, in my opinion.

2024-02-11 16:25 UTC, schitcrafter commented
@maxwai Changes look good but I'd at least like to know if we want the EnvFilter or not, then we can merge this (plus #199 and after some testing #201 )

2024-02-11 16:32 UTC, maxwai commented
The Env Filter is not necessary here. we can still switch to trace using the env for the console and file outputs

2024-02-11 17:10 UTC, merged

2024-02-11 17:21 UTC, schitcrafter commented
Yeah okay but...that's not why I'd use EnvFilter. I'd use it because if, for example, I wanted to debug something with subject commands, and switched to trace globally for that, I'd have tons of unnecessary output. With EnvFilter I could cut down on that by only specifying trace for that specific module. But if you don't wanna merge it